services:
  - type: web
    name: cv-screening-system
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        fromVariable: SECRET_KEY
      - key: DATABASE_URL
        fromVariable: DATABASE_URL
    plan: free 