services:
  - type: web
    name: cv-screening-system
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        fromVariable: SECRET_KEY
      - key: DATABASE_URL
        fromVariable: DATABASE_URL
    plan: free
