services:
  - type: web
    name: cv-screening-system
    env: python
    buildCommand: |
      # Install system dependencies
      apt-get update && apt-get install -y tesseract-ocr poppler-utils
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: SECRET_KEY
        fromVariable: SECRET_KEY
      - key: DATABASE_URL
        fromVariable: DATABASE_URL
    plan: free
    runtime: python3 